// src/pages/Affiliate.jsx
import React from "react";
import Footer from "../../components/Footer";
import {
  FaLink,
  FaBullseye,
  FaShareAlt,
  FaChartLine,
  FaMoneyBillWave,
  FaRocket,
} from "react-icons/fa";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { FaGlobe, FaHandshake, FaMoneyCheckAlt, FaUsers } from "react-icons/fa";
import { MdInventory, MdTrendingUp, MdGroups } from "react-icons/md";
import { Helmet } from "react-helmet";

const Affiliate = () => {
  
  const navigate = useNavigate();

  const steps = [
    {
      icon: <FaLink size={28} className="text-red-600" />,
      title: "Join Affiliate Programme",
      description:
        "Sign up to affiliate programmes that align with your interests and target audience.",
    },
    {
      icon: <FaBullseye size={28} className="text-red-500" />,
      title: "Receive Unique Link",
      description:
        "After signing up, receive a unique affiliate link that tracks your sales and leads.",
    },
    {
      icon: <FaShareAlt size={28} className="text-red-400" />,
      title: "Promote Products & Services",
      description:
        "Promote products via website blogs, social media, ads, and other channels.",
    },
    {
      icon: <FaChartLine size={28} className="text-red-500" />,
      title: "Track Leads or Sales",
      description:
        "Monitor clicks, conversions, and actions performed through your affiliate link.",
    },
    {
      icon: <FaMoneyBillWave size={28} className="text-red-600" />,
      title: "Commission Received",
      description:
        "Earn a percentage or fixed amount for every successful conversion you generate.",
    },
    {
      icon: <FaRocket size={28} className="text-red-700" />,
      title: "Continuous Optimization",
      description:
        "We constantly analyze and optimize strategies to ensure higher conversions and better revenue for both affiliates and companies.",
    },
  ];

  return (
    <div className="text-white font-sans min-h-screen flex flex-col">
      <Helmet>
      <title>Skyrocket Revenue with TheSecureMedia Affiliates</title>
      <meta
        name="description"
        content="Supercharge your brand’s growth with TheSecureMedia’s expert affiliate marketing services. Unlock powerful strategies to boost revenue."
      />
            <link rel="canonical" href="https://thesecuremedia.com/services/affiliate-marketing" />

    </Helmet>
      
      {/* ================= HERO ================= */}
      <section className="min-h-screen flex items-center px-6 md:px-20 bg-gradient-to-r from-red-600 to-red-800">
        <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 items-center gap-10">
          {/* Left Text */}
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h1 className="text-4xl md:text-5xl mb-6">
              Transform your traffic into revenue with Smart Affiliate Strategies
            </h1>
            <p className="text-lg md:text-xl text-white">
              Transform your website traffic into a steady stream of income with
              smart affiliate strategies. Performance-based marketing lets
              companies pay commissions for sales or leads generated by
              affiliates, making it a win-win scenario.
            </p>
            <button
              onClick={() => navigate("/contact-us")}
              className="mt-6 bg-white text-red-600 font-bold px-8 py-3 rounded-full shadow-md hover:bg-gray-100 transition"
            >
              Get Started
            </button>
          </motion.div>

          {/* Right Image */}
          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
          >
            <img
              src="/afff.png"
              alt="Affiliate Marketing"
              className="w-full"
            />
          </motion.div>
        </div>
      </section>

      {/* ================= HOW AFFILIATES WORK ================= */}
      <section className="py-20 px-6 md:px-20 bg-gray-50 text-black">
        <div className="max-w-6xl mx-auto text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            How  <span className="text-red-600">Affiliates</span> Work
          </h2>
          <p className="text-gray-600 text-lg md:text-xl max-w-3xl mx-auto">
            Follow these steps to start earning through affiliate marketing:
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-10 max-w-6xl mx-auto">
          {steps.map((step, index) => (
            <div
              key={index}
              className="bg-white rounded-xl shadow-lg p-6 flex flex-col items-center text-center hover:shadow-xl transition-shadow"
            >
              <div className="mb-4">{step.icon}</div>
              <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
              <p className="text-gray-600 text-sm">{step.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ================= PUBLISHERS ================= */}
      <section className="py-20 px-6 md:px-20 bg-white text-center">
        <h2 className="text-4xl font-bold mb-6 text-gray-800">
          <span className="text-red-600">SAM</span> for <span className="text-red-600">Publishers</span>
        </h2>
        <p className="text-lg text-gray-600 mb-12 max-w-3xl mx-auto">
          Together, we can promote ads, maintain traffic, and assist you in
          receiving the commissions you earn.
        </p>

        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
          <div className="p-8 bg-gray-50 rounded-2xl shadow-md hover:shadow-xl hover:-translate-y-1 transition">
            <FaGlobe className="text-4xl text-red-600 mb-4 mx-auto" />
            <h3 className="font-semibold text-black text-xl mb-2">Global Brands</h3>
            <p className="text-gray-600">
              Partner with well-known, game-changing brands worldwide.
            </p>
          </div>
          <div className="p-8 bg-gray-50 rounded-2xl shadow-md hover:shadow-xl hover:-translate-y-1 transition">
            <FaHandshake className="text-4xl text-red-600 mb-4 mx-auto" />
            <h3 className="  text-black font-semibold text-xl mb-2">
              Best Converting Offers
            </h3>
            <p className="text-gray-600">
              Access high-converting offers with 24/7 customer support.
            </p>
          </div>
          <div className="p-8 bg-gray-50 rounded-2xl shadow-md hover:shadow-xl hover:-translate-y-1 transition">
            <FaMoneyCheckAlt className="text-4xl text-red-600 mb-4 mx-auto" />
            <h3 className="  text-black font-semibold text-xl mb-2">Secure Payments</h3>
            <p className="text-gray-600">
              We support RTGS and NEFT direct payment methods.
            </p>
          </div>
          <div className="p-8 bg-gray-50 rounded-2xl shadow-md hover:shadow-xl hover:-translate-y-1 transition">
            <FaUsers className="text-4xl  text-red-600 mb-4 mx-auto" />
            <h3 className="  text-black font-semibold text-xl mb-2">Publisher Support</h3>
            <p className="text-gray-600">
              Assistance for both new and experienced publishers.
            </p>
          </div>
        </div>
      </section>

      {/* ================= ADVERTISERS ================= */}
      <section className="py-20 px-6 md:px-20 bg-gray-50 text-center">
        <h2 className="text-4xl font-bold mb-6 text-gray-800">
          <span className="text-red-600"> SAM</span> for<span className="text-red-600">   Advertisers</span>
        </h2>
        <p className="text-lg text-gray-600 mb-12 max-w-3xl mx-auto">
          Our media buying team helps companies achieve results and boost their
          online & mobile presence through effective advertising strategies.
        </p>

        <div className="grid gap-8 md:grid-cols-3">
          <div className="p-8 bg-white rounded-2xl shadow-md hover:shadow-xl hover:-translate-y-1 transition">
            <MdInventory className="text-4xl text-red-600 mb-4 mx-auto" />
            <h3 className="  text-black font-semibold text-xl mb-2">Smart Inventory</h3>
            <p className="text-gray-600">
              Effective inventory management for better campaign delivery.
            </p>
          </div>
          <div className="p-8 bg-white rounded-2xl shadow-md hover:shadow-xl hover:-translate-y-1 transition">
            <MdTrendingUp className="text-4xl text-red-600 mb-4 mx-auto" />
            <h3 className="  text-black font-semibold text-xl mb-2">ROI Maximization</h3>
            <p className="text-gray-600">
              Choosing the best medium & module for maximum ROI.
            </p>
          </div>
          <div className="p-8 bg-white rounded-2xl shadow-md hover:shadow-xl hover:-translate-y-1 transition">
            <MdGroups className="text-4xl text-red-600 mb-4 mx-auto" />
            <h3 className=" text-black  font-semibold text-xl mb-2">Client Growth</h3>
            <p className="text-gray-600">
              Build a stronger client base with targeted ad strategies.
            </p>
          </div>
        </div>
      </section>

      
      {/* ================= FOOTER ================= */}
      <Footer />
    </div>
  );
};

export default Affiliate;
